name: Compilation push on master

on:
  push:
    branches:
      - master
    paths:
      - 'scripts/tvm_cli/**'
      - '**.onnx'
      - '**.pb'
      - '.github/workflows/compilation-push-master.yaml'

jobs:
  compile-push-bucket:
    if: github.repository_owner == 'autowarefoundation'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
    container:
      image: autoware/model-zoo-tvm-cli:bleedingedge
    steps:
      - name: Install LFS
        run: |
          apt-get update
          apt-get install git-lfs

      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Generate and save artifacts
        env:
          AWS_S3_BUCKET: autoware-modelzoo
          AWS_ACCESS_KEY_ID: ${{ secrets.MODELZOO_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MODELZOO_S3_KEY }}
          AWS_REGION: us-east-2
        run: |
          cp -r . /tmp
          cd /tmp
          ./scripts/tvm_cli/tvm_cli.py test
          tar -C /tmp/neural_networks/`uname -m` \
            -czf networks-`uname -m`.tar.gz .
          pip install --quiet --no-cache-dir awscli==1.19.98
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          ${AWS_ACCESS_KEY_ID}
          ${AWS_SECRET_ACCESS_KEY}
          ${AWS_REGION}
          text
          EOF
          aws s3 cp networks-`uname -m`.tar.gz s3://autoware-modelzoo/ \
            --profile s3-sync-action --acl public-read
          aws configure --profile s3-sync-action <<-EOF > /dev/null 2>&1
          null
          null
          null
          text
          EOF
