name: Compilation push on master

on:
  push:
    branches:
      - master
    paths:
      - 'scripts/tvm_cli/**'
      - '**.onnx'
      - '**.pb'

jobs:
  compile-push-bucket:
    if: github.repository_owner == 'autowarefoundation'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, ARM64]
    container:
      image: autoware/model-zoo-tvm-cli:bleedingedge
      volumes:
        - /tmp/artifacts:/tmp/artifacts
    steps:
      - name: Install LFS
        run: |
          apt-get update
          apt-get install git-lfs

      - name: Checkout
        uses: actions/checkout@v2
        with:
          lfs: true

      - name: Generate artifacts
        run: |
          cp -r . /tmp
          cd /tmp
          ./scripts/tvm_cli/tvm_cli.py test
          tar -czf networks-`uname -m`.tar.gz -C /tmp/neural_networks/`uname -m`/ .
          mv networks-`uname -m`.tar.gz /tmp/artifacts

      - name: Save artifacts
        uses: jakejarvis/s3-sync-action@v0.5.1
        with:
          args: --acl public-read --follow-symlinks
        env:
          AWS_S3_BUCKET: autoware-modelzoo
          AWS_ACCESS_KEY_ID: ${{ secrets.MODELZOO_S3_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.MODELZOO_S3_KEY }}
          SOURCE_DIR: '/tmp/artifacts'
